language: php
sudo: false

php:
  - 7.0

env:
  - APP_ENV=production

before_script:
  - composer self-update
  - cp .env.example .env
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate

script:
  - ./vendor/bin/phpunit
